name: flex_id
description: Like nanoid but sortable and more customizible.
version: 0.0.1
repository: https://github.com/fbede/tiny_id

environment:
  sdk: ^3.1.2

dependencies:
  characters: ^1.3.0
  collection: ^1.18.0
  fixnum: ^1.1.0

dev_dependencies:
  all_lint_rules_community: ^0.0.38
  test: ^1.21.0
